#!/usr/bin/env bash
# Configures a new server and adds header 'X-Served-By'

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
service nginx restart

