#!/usr/bin/env bash
# Installs and configures HAproxy

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" >/etc/default/haproxy

FRONT="frontend 20332-lb-01\n\tbind *:80\n\tmode http\n\n\tdefault_backend web_backend"
BACK="backend web-backend\n\tbalance roundrobin\n\tserver 20332-web-01 3.234.246.193:80 check\n\tserver 20332-web-02 3.234.222.194:80 check"

sudo echo -e $FRONT >>/etc/haproxy/haproxy.cfg
sudo echo -e $BACK >>/etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
