#!/usr/bin/env bash
# Display hours from 0 to 12
# Display minutes from 1 to 59

HOURS=O
while [[ $HOURS -lt 13 ]]
do
    echo "Hour: $HOURS"

    MINUTES=1
    while [[ $MINUTES -lt 60 ]]
    do
        echo $MINUTES
        ((MINUTES += 1))

    done
    ((HOURS+=1))

done
